# Generated by Django 3.2.9 on 2021-11-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cedula_user_documento_identificacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='responsable',
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.responsable')),
            ],
        ),
    ]
