# Generated by Django 3.2.9 on 2021-11-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211129_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fk_usuario',
            new_name='responsable',
        ),
    ]
