# Generated by Django 3.2.9 on 2021-12-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_fk_usuario_tarea_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='responsable',
            new_name='fkusuario',
        ),
    ]
